name = "Prodeb"
author = "lucas"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b05c8c8240b2c7357e6c5b98a406b396329cef80199ea68e287e4cbe7c84e9d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
