name = "Prodeb"
author = "lucas"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5239f39f76b743c56d0abb971fef97207947bab8858e7abacf1e9e7fc5c8ed45"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
